import { parse as peggyParse } from "./peggy/generated";
import { ER, ERSchema } from "../types/parser/ER";

// type safe wrapper for the parser generated by peggy
/**
 * Parses an ERDoc string into an ER object
 * @param {string} erString - The ERDoc string to parse
 * @return {ER} ER object representing the successfully parsed ERDoc string
 * @throws {SyntaxError} If the ERDoc string is not valid
 */
export const parse = (erString: string): ER => {
  const parsed = peggyParse(erString);
  return ERSchema.parse(parsed);
};
